[package]
name = "jammdb_bincode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.3"
jammdb = "0.11.0"
peroxide = "0.34.4"
